### ISSUE TITLE
Would you consider re-licensing this repository?

### ISSUE THREAD

**Issue by arfon** [Shammah/boo-sublime#8]
Hello there, we'd love to use this library to syntax-highlight files on GitHub but in order to do so we need this library to have a more permissive license.

If you don't have any particular reason for choosing GPL would you be willing to consider switching this to a more permissive license such as MIT, BSD or Apache 2?

Many thanks
Arfon (GitHub Staff)

**Comment by Shammah** [comment]
I think you are right, the GPL license offers no benefit at this moment.
@oferei I have included you as well in the copyrights, is this okay to you?

The preliminary license can be found at https://github.com/Shammah/boo-sublime/commit/d5344462c4209d978e5eb67a067b911c729793e8

**Comment by oferei** [comment]
MIT is fine by me. Permissive it is.

**Comment by arfon** [comment]
:zap: many thanks folks.
